//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAV_PF_AlejandroRodriguezQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaImpuesto
    {
        public int FacturaImpuestoId { get; set; }
        public int FacturaId { get; set; }
        public int ImpuestoId { get; set; }
        public decimal PorcentajeAplicado { get; set; }
        public decimal MontoImpuesto { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Impuesto Impuesto { get; set; }
    }
}
