//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAV_PF_AlejandroRodriguezQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Impuesto()
        {
            this.FacturaImpuesto = new HashSet<FacturaImpuesto>();
        }
    
        public int ImpuestoId { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public decimal Porcentaje { get; set; }
        public bool Activo { get; set; }
        public System.DateTime VigenteDesde { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaImpuesto> FacturaImpuesto { get; set; }
    }
}
